DROP DATABASE IF EXISTS economics_db ;
CREATE DATABASE economics_db;
use economics_db;

CREATE TABLE teacher 
(
	id VARCHAR(20) PRIMARY KEY,name VARCHAR(25) NOT NULL,
	password VARCHAR(32) NOT NULL,
	college VARCHAR(50) NOT NULL,
	course VARCHAR(50) NOT NULL
)ENGINE=INNODB;
ALTER TABLE teacher ADD COLUMN isAddChat INT NOT NULL;

CREATE TABLE student 
(
	id VARCHAR(20) PRIMARY KEY,name VARCHAR(25) NOT NULL,
	password VARCHAR(32) NOT NULL,
	college VARCHAR(50) NOT NULL,
	major VARCHAR(50) NOT NULL,class INT NOT NULL,
	tId VARCHAR(20),
	FOREIGN KEY (tId) REFERENCES teacher(id) ON DELETE CASCADE
)ENGINE=INNODB;


CREATE TABLE QuestionLibrary 
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	type INT NOT NULL,selected INT NOT NULL,
	tId VARCHAR(20),
	name VARCHAR(50),
	createTime TIMESTAMP NOT NULL,
	FOREIGN KEY (tId) REFERENCES teacher(id) ON DELETE CASCADE
)ENGINE=INNODB;
-- 
CREATE TABLE Question
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	type INT NOT NULL,content VARCHAR(500) NOT NULL,
	answer VARCHAR(100) NOT NULL,mark INT,
	resolve VARCHAR(500),date TIMESTAMP NOT NULL,
	qlId INT,
	FOREIGN KEY (qlId) REFERENCES QuestionLibrary(id)
	ON DELETE CASCADE
)ENGINE=INNODB;
ALTER TABLE question ADD COLUMN oder INT NOT NULL;


CREATE TABLE Choose
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	content VARCHAR(500) NOT NULL,
	qId INT,
	FOREIGN KEY (qId) REFERENCES Question(id)
	ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE attachment 
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	type INT NOT NULL,
	content VARCHAR(500) NOT NULL,
	qId INT,
	FOREIGN KEY (qId) REFERENCES Question(id)
	ON DELETE CASCADE
)ENGINE=INNODB;


CREATE TABLE ExaminationResult
(
	sId VARCHAR(20),
	qlId INT, 
	mark INT NOT NULL,
	PRIMARY KEY(sId,qlId),
	FOREIGN KEY (sId) REFERENCES student(id) ON DELETE CASCADE,
	FOREIGN KEY (qlId) REFERENCES questionlibrary(id) ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE filemodel
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	url VARCHAR(100) NOT NULL, 
	name VARCHAR(100) NOT NULL,
	tId VARCHAR(20),
	FOREIGN KEY (tId) REFERENCES teacher(id) ON DELETE CASCADE
)ENGINE=INNODB;


CREATE TABLE loger 
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	url VARCHAR(100) NOT NULL,
	exception VARCHAR(200) ,
	execMethod VARCHAR(100) NOT NULL,
	date TIMESTAMP NOT NULL
)ENGINE=INNODB;


CREATE TABLE admin 
(
	id VARCHAR(20) PRIMARY KEY,name VARCHAR(25) NOT NULL,
	password VARCHAR(32) NOT NULL,
	logourl VARCHAR(100)
)ENGINE=INNODB;

CREATE TABLE chatroom 
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	stuId VARCHAR(20) NOT NULL,
	teaId VARCHAR(20) NOT NULL,
	logourl VARCHAR(100),
	stuRead INT NOT NULL,
	teaRead INT NOT NULL,
	lastChatTime TIMESTAMP NOT NULL,
	stuName VARCHAR(50) NOT NULL,
	teaName VARCHAR(50) NOT NULL,
	starChat INT NOT NULL,
	FOREIGN KEY (stuId) REFERENCES student(id) ON DELETE CASCADE,
	FOREIGN KEY (teaId) REFERENCES teacher(id) ON DELETE CASCADE
)ENGINE=INNODB;
-- 
CREATE TABLE message 
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	type INT NOT NULL,
	content VARCHAR(150) NOT NULL,
	fromId VARCHAR(20) NOT NULL,
	fromName VARCHAR(25) NOT NULL,
	toId VARCHAR(20) NOT NULL,
	date TIMESTAMP NOT NULL,
	chatRoomId INT ,
	fileName VARCHAR(100),
	FOREIGN KEY (chatRoomId) REFERENCES chatroom(id) ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE user_message 
(
	id VARCHAR(20) PRIMARY KEY ,
	hasMess INT NOT NULL
)ENGINE=INNODB;

INSERT INTO admin (id,name,password) 
VALUES('1234567890','管理员','E10ADC3949BA59ABBE56E057F20F883E');

